# Generated by Django 3.2.9 on 2021-11-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0002_repository'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='url',
            field=models.CharField(default='https://github.com/bisooo/AUXBox', max_length=180, verbose_name='repo url'),
            preserve_default=False,
        ),
    ]
