# Generated by Django 3.2.9 on 2021-12-01 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0003_repository_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PullRequestWait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField()),
                ('merged_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField()),
                ('merged', models.BooleanField()),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='git.repository')),
            ],
        ),
    ]
